export const GET_USERS_BY_NAME = 'GET_USERS_BY_NAME';
export const GET_USERS_BY_NAME_RECEIVED = 'GET_USERS_BY_NAME_RECEIVED';
export const GET_USERS_BY_NAME_FAILED = 'GET_USERS_BY_NAME_FAILED';

export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const GET_USER_PROFILE_RECEIVED = 'GET_USER_PROFILE_RECEIVED';
export const GET_USER_PROFILE_FAILED = 'GET_USER_PROFILE_FAILED';